/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 check.glb -s -k 
*/

import React, { useEffect } from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'



export function Check(props) {
  const group = React.useRef()
  const cheerfulRef = React.useRef()
  const happyRef = React.useRef()
  const neutralRef = React.useRef()
  const sadRef = React.useRef()
  
  const { scene, animations } = useGLTF('/models/check.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions, names } = useAnimations(animations, group)

  const showEmotion = (emotion) => {
    const emotions = {
      cheerful: cheerfulRef.current,
      happy: happyRef.current,
      neutral: neutralRef.current,
      sad: sadRef.current,
    }

    Object.values(emotions).forEach((ref) => {
      if (ref) ref.visible = false
    })

    const targetEmotion = emotions[emotion.toLowerCase()]
    if (targetEmotion) {
      targetEmotion.visible = true
    }
  }
  React.useImperativeHandle(group, () => ({
    showEmotion,
  }), [])

  useEffect(() => {
    const emotions = ['cheerful', 'happy', 'neutral', 'sad']
    let currentIndex = 0

    const interval = setInterval(() => {
      showEmotion(emotions[currentIndex])
      currentIndex = (currentIndex + 1) % emotions.length
    }, 5000)

    // Show the first emotion immediately
    showEmotion(emotions[0])

    return () => clearInterval(interval)
  }, [])

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Armature" rotation={[Math.PI / 2, 0, 0]}>
          <primitive object={nodes.mixamorigHips} />
          <group name="cheerful" ref={cheerfulRef} visible={false}>
            <skinnedMesh name="ChatGPT_Image_Jan_21,_2026,_08_16_13_PM005" geometry={nodes['ChatGPT_Image_Jan_21,_2026,_08_16_13_PM005'].geometry} material={materials.cheerful_eyes} skeleton={nodes['ChatGPT_Image_Jan_21,_2026,_08_16_13_PM005'].skeleton} />
            <skinnedMesh name="ChatGPT_Image_Jan_21,_2026,_08_16_13_PM005_1" geometry={nodes['ChatGPT_Image_Jan_21,_2026,_08_16_13_PM005_1'].geometry} material={materials.cheerful_mouth} skeleton={nodes['ChatGPT_Image_Jan_21,_2026,_08_16_13_PM005_1'].skeleton} />
          </group>
          <group name="Happy" ref={happyRef} visible={false}>
            <skinnedMesh name="ChatGPT_Image_Jan_21,_2026,_08_16_13_PM002" geometry={nodes['ChatGPT_Image_Jan_21,_2026,_08_16_13_PM002'].geometry} material={materials.Happy_eyes} skeleton={nodes['ChatGPT_Image_Jan_21,_2026,_08_16_13_PM002'].skeleton} />
            <skinnedMesh name="ChatGPT_Image_Jan_21,_2026,_08_16_13_PM002_1" geometry={nodes['ChatGPT_Image_Jan_21,_2026,_08_16_13_PM002_1'].geometry} material={materials.Happy_mouth} skeleton={nodes['ChatGPT_Image_Jan_21,_2026,_08_16_13_PM002_1'].skeleton} />
          </group>
          <group name="neutral" ref={neutralRef} visible={true}>
            <skinnedMesh name="ChatGPT_Image_Jan_21,_2026,_08_16_13_PM004" geometry={nodes['ChatGPT_Image_Jan_21,_2026,_08_16_13_PM004'].geometry} material={materials.neutral_eyes} skeleton={nodes['ChatGPT_Image_Jan_21,_2026,_08_16_13_PM004'].skeleton} />
            <skinnedMesh name="ChatGPT_Image_Jan_21,_2026,_08_16_13_PM004_1" geometry={nodes['ChatGPT_Image_Jan_21,_2026,_08_16_13_PM004_1'].geometry} material={materials.neutral_mouth} skeleton={nodes['ChatGPT_Image_Jan_21,_2026,_08_16_13_PM004_1'].skeleton} />
          </group>
          <group name="Sad" ref={sadRef} visible={false}>
            <skinnedMesh name="ChatGPT_Image_Jan_21,_2026,_08_16_13_PM003" geometry={nodes['ChatGPT_Image_Jan_21,_2026,_08_16_13_PM003'].geometry} material={materials.sad_eyes} skeleton={nodes['ChatGPT_Image_Jan_21,_2026,_08_16_13_PM003'].skeleton} />
            <skinnedMesh name="ChatGPT_Image_Jan_21,_2026,_08_16_13_PM003_1" geometry={nodes['ChatGPT_Image_Jan_21,_2026,_08_16_13_PM003_1'].geometry} material={materials.sad_mouth} skeleton={nodes['ChatGPT_Image_Jan_21,_2026,_08_16_13_PM003_1'].skeleton} />
          </group>
        </group>
        <skinnedMesh name="tripo_node_8cdfe2ae" geometry={nodes.tripo_node_8cdfe2ae.geometry} material={materials.tripo_mat_8cdfe2ae} skeleton={nodes.tripo_node_8cdfe2ae.skeleton} />
      </group>
    </group>
  )
}

useGLTF.preload('/check.glb')
